/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlimentosRouteImport } from './routes/alimentos'
import { Route as JogoRouteImport } from './routes/jogo'
import { Route as MeuDiaRouteImport } from './routes/meu-dia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentosRoute = AlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoRoute = JogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuDiaRoute = MeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alimentos': typeof AlimentosRoute
  '/jogo': typeof JogoRoute
  '/meu-dia': typeof MeuDiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alimentos': typeof AlimentosRoute
  '/jogo': typeof JogoRoute
  '/meu-dia': typeof MeuDiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alimentos': typeof AlimentosRoute
  '/jogo': typeof JogoRoute
  '/meu-dia': typeof MeuDiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alimentos' | '/jogo' | '/meu-dia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alimentos' | '/jogo' | '/meu-dia'
  id: '__root__' | '/' | '/alimentos' | '/jogo' | '/meu-dia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlimentosRoute: typeof AlimentosRoute
  JogoRoute: typeof JogoRoute
  MeuDiaRoute: typeof MeuDiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentos': {
      id: '/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof AlimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-dia': {
      id: '/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof MeuDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlimentosRoute: AlimentosRoute,
  JogoRoute: JogoRoute,
  MeuDiaRoute: MeuDiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
